language: python
python:
- '2.6'
branches:
  only:
  - travis
install:
- sudo apt-get install maven2
- pip install jinja2
before_script:
- cd touchforms/offline/
- ./travis_setup.sh
script: python build.py $JNLP_ROOT
env:
  global:
  - JNLP_ROOT=https://www.commcarehq.org/offline-cloudcare/
  - secure: HT8zKXlWewOTM+0PQ3/bL8arasqHjTYmF96a/Gz+3g7y6a27yOvLXctCsj2omynww+FJ4JjkmzUMsUaBAc3RB7PPTuqacZ/LzUXDa59rpWEIWLkyzqLSRSnbEykchBy6M5e3N7UZx615WAzrcNnh8uE/C/cIwUQ7+knXwJUBzec=
  - secure: eDnESWSQipxY0ADPfTXZn723phAFNRo/YVWYaqabnAf86zUBc9oROOfplrdjbQafE/f4GrOCHVpwVXmltAkOxfMFS0W9VkpkaNcys9p1M9S2cu10ytQnltblu6kDh5HeLVcCPHHBqvUMinKS2iQGK9NvR940aw6Aa7oWa1Tt8dI=
  - secure: Kz+OmDvLuEKQ7+zu+xloz+I+Qg1dYmwzl/KexKzK4CwMNoRSOqDpwybg/lOeHGseeoPW31TNIFRwa3SLntOSoTLOMURtbZz6cXsgiCIX8usLkXiUhoUG5B/ptpzdqqlqxY+sqrDuytmkfPXLvs1y590SfO3q/zNcBZVvhJZ8++A=
