language: python
python:
  - "2.7"
services:
  - redis-server
before_install: 
  - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.5.3/jython-installer-2.5.3.jar'
  - wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH;
branches:
  only:
      - master
install:
  - "cp touchforms/backend/localsettings.py.example touchforms/backend/localsettings.py"
  - "pip install -r touchforms/test_requirements.txt"
script: "./run_tests.sh"
